# Generated by Django 2.2.1 on 2019-05-30 06:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('date_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GPSDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('terryx_station_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RunSQL(
            """
                CREATE TABLE gps_tracking_app_log (
                gps_id  integer NOT NULL,
                location  geometry(Point,4326) NOT NULL,
                date_time TIMESTAMPTZ NOT NULL
                );
                SELECT create_hypertable('gps_tracking_app_log', 'date_time', chunk_time_interval => interval '2 week');
            """
        ),
    ]
