# Generated by Django 2.2.3 on 2019-07-03 06:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gps_tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpsdevice',
            options={'verbose_name_plural': 'GPSDevices'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'managed': False, 'verbose_name_plural': 'Logs'},
        ),
        migrations.CreateModel(
            name='GeofenceZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('gps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps_tracking_app.GPSDevice')),
            ],
            options={
                'verbose_name_plural': 'GeofenceZones',
            },
        ),
    ]
