# Generated by Django 2.2.3 on 2019-07-03 09:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps_tracking_app', '0002_auto_20190703_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofencezone',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
